apiVersion: v1
kind: Service
metadata:
  name: guessthenumber-service
  namespace: default
spec:
  selector:
    app: guessthenumber
  type: NodePort
  ports:
  - name: guessthenumber-service
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30002
