apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  namespace: default
  labels:
    app: {{ .Values.appName }}
spec:
  selector:
    app: {{ .Values.appName }}
  type: LoadBalancer
  ports:
  - name: guessthenumber-service
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30002
